const resources = {
  aiTools: [
    {
      id: "chatgpt",
      name: "ChatGPT",
      description:
        "Advanced language model for code explanation, debugging, and problem-solving",
      icon: "fa-comment-dots",
      tags: ["ai", "free", "coding", "writing"],
      url: "https://chat.openai.com",
      category: "AI Assistant",
    },
    {
      id: "deepseek",
      name: "DeepSeek Coder",
      description: "AI-powered code completion and generation tool",
      icon: "fa-code",
      tags: ["ai", "free", "coding"],
      url: "https://www.deepseek.com",
      category: "Code Assistant",
    },
    {
      id: "gemini",
      name: "Google Gemini",
      description: "Google's multimodal AI for code assistance and generation",
      icon: "fa-google",
      tags: ["ai", "premium", "coding"],
      url: "https://cloud.google.com/vertex-ai",
      category: "Code Assistant",
    },
    {
      id: "github-copilot",
      name: "GitHub Copilot",
      description: "AI pair programmer that suggests code completions",
      icon: "fa-github",
      tags: ["ai", "premium", "coding"],
      url: "https://github.com/features/copilot",
      category: "Code Assistant",
    },
    {
      id: "claude",
      name: "Claude AI",
      description: "Advanced AI assistant for coding and technical writing",
      icon: "fa-robot",
      tags: ["ai", "premium", "coding", "writing"],
      url: "https://www.anthropic.com/claude",
      category: "AI Assistant",
    },
    {
      id: "dalle",
      name: "DALL·E 3",
      description: "AI image generation for design assets and illustrations",
      icon: "fa-image",
      tags: ["ai", "premium", "design"],
      url: "https://openai.com/dall-e-3",
      category: "Design",
    },
    {
      id: "midjourney",
      name: "Midjourney",
      description: "AI art and image generation tool",
      icon: "fa-paintbrush",
      tags: ["ai", "premium", "design"],
      url: "https://www.midjourney.com",
      category: "Design",
    },
  ],
  freeResources: [
    {
      id: "unsplash",
      name: "Unsplash",
      description: "Beautiful free images & pictures",
      icon: "fa-camera",
      tags: ["free", "images"],
      url: "https://unsplash.com",
      category: "Images",
    },
    {
      id: "pexels",
      name: "Pexels",
      description: "Free stock photos & videos",
      icon: "fa-image",
      tags: ["free", "images"],
      url: "https://www.pexels.com",
      category: "Images",
    },
    {
      id: "pixabay",
      name: "Pixabay",
      description: "Free images & royalty-free stock",
      icon: "fa-images",
      tags: ["free", "images"],
      url: "https://pixabay.com",
      category: "Images",
    },
    {
      id: "flaticon",
      name: "Flaticon",
      description: "Free vector icons & stickers",
      icon: "fa-icons",
      tags: ["free", "icons"],
      url: "https://www.flaticon.com",
      category: "Icons",
    },
    {
      id: "fontawesome",
      name: "Font Awesome",
      description: "Icon library and toolkit",
      icon: "fa-font-awesome",
      tags: ["free", "icons"],
      url: "https://fontawesome.com",
      category: "Icons",
    },
    {
      id: "material-icons",
      name: "Material Icons",
      description: "Google's Material Design icons",
      icon: "fa-shapes",
      tags: ["free", "icons"],
      url: "https://fonts.google.com/icons",
      category: "Icons",
    },
    {
      id: "heroicons",
      name: "Heroicons",
      description: "Beautiful hand-crafted SVG icons",
      icon: "fa-pen-fancy",
      tags: ["free", "icons"],
      url: "https://heroicons.com",
      category: "Icons",
    },
    {
      id: "figma-community",
      name: "Figma Community",
      description: "Free design resources and UI kits",
      icon: "fa-figma",
      tags: ["free", "ui-kits"],
      url: "https://www.figma.com/community",
      category: "UI Kits",
    },
  ],
  frontendFrameworks: [
    {
      id: "react",
      name: "React",
      description: "A JavaScript library for building user interfaces",
      icon: "fa-react",
      tags: ["free", "javascript", "frontend"],
      url: "https://reactjs.org",
      category: "JavaScript",
    },
    {
      id: "vue",
      name: "Vue.js",
      description: "Progressive JavaScript Framework",
      icon: "fa-vuejs",
      tags: ["free", "javascript", "frontend"],
      url: "https://vuejs.org",
      category: "JavaScript",
    },
    {
      id: "angular",
      name: "Angular",
      description: "Platform for building mobile and desktop web applications",
      icon: "fa-angular",
      tags: ["free", "javascript", "frontend"],
      url: "https://angular.io",
      category: "JavaScript",
    },
    {
      id: "tailwind",
      name: "Tailwind CSS",
      description: "Utility-first CSS framework",
      icon: "fa-wind",
      tags: ["free", "css"],
      url: "https://tailwindcss.com",
      category: "CSS",
    },
    {
      id: "bootstrap",
      name: "Bootstrap",
      description: "Popular CSS framework for responsive sites",
      icon: "fa-bootstrap",
      tags: ["free", "css"],
      url: "https://getbootstrap.com",
      category: "CSS",
    },
    {
      id: "chakra",
      name: "Chakra UI",
      description: "Simple, modular component library",
      icon: "fa-universal-access",
      tags: ["free", "ui"],
      url: "https://chakra-ui.com",
      category: "UI",
    },
  ],
  backendFrameworks: [
    {
      id: "django",
      name: "Django",
      description: "High-level Python web framework",
      icon: "fa-python",
      tags: ["free", "python"],
      url: "https://www.djangoproject.com",
      category: "Python",
    },
    {
      id: "flask",
      name: "Flask",
      description: "Lightweight WSGI web application framework",
      icon: "fa-flask",
      tags: ["free", "python"],
      url: "https://flask.palletsprojects.com",
      category: "Python",
    },
    {
      id: "fastapi",
      name: "FastAPI",
      description: "Modern, fast web framework for Python",
      icon: "fa-bolt",
      tags: ["free", "python"],
      url: "https://fastapi.tiangolo.com",
      category: "Python",
    },
    {
      id: "express",
      name: "Express.js",
      description: "Fast, unopinionated web framework for Node.js",
      icon: "fa-node-js",
      tags: ["free", "node"],
      url: "https://expressjs.com",
      category: "Node.js",
    },
    {
      id: "nestjs",
      name: "NestJS",
      description: "Progressive Node.js framework",
      icon: "fa-feather",
      tags: ["free", "node"],
      url: "https://nestjs.com",
      category: "Node.js",
    },
  ],
  mobileDev: [
    {
      id: "flutter",
      name: "Flutter",
      description: "Google's UI toolkit for cross-platform apps",
      icon: "fa-mobile-screen",
      tags: ["free", "cross-platform"],
      url: "https://flutter.dev",
      category: "Cross-Platform",
    },
    {
      id: "react-native",
      name: "React Native",
      description: "Build native apps using React",
      icon: "fa-react",
      tags: ["free", "cross-platform"],
      url: "https://reactnative.dev",
      category: "Cross-Platform",
    },
    {
      id: "swiftui",
      name: "SwiftUI",
      description: "Apple's UI framework for iOS",
      icon: "fa-apple",
      tags: ["free", "ios"],
      url: "https://developer.apple.com/xcode/swiftui",
      category: "iOS",
    },
    {
      id: "jetpack",
      name: "Jetpack Compose",
      description: "Modern UI toolkit for Android",
      icon: "fa-android",
      tags: ["free", "android"],
      url: "https://developer.android.com/jetpack/compose",
      category: "Android",
    },
  ],
  gameDev: [
    {
      id: "unity",
      name: "Unity",
      description: "Cross-platform game development engine",
      icon: "fa-gamepad",
      tags: ["free", "engines"],
      url: "https://unity.com",
      category: "Engines",
    },
    {
      id: "phaser",
      name: "Phaser",
      description: "HTML5 game framework",
      icon: "fa-rocket",
      tags: ["free", "frameworks"],
      url: "https://phaser.io",
      category: "Frameworks",
    },
  ],
  designTools: [
    {
      id: "coolors",
      name: "Coolors",
      description: "Color schemes generator",
      icon: "fa-palette",
      tags: ["free", "colors"],
      url: "https://coolors.co",
      category: "Colors",
    },
    {
      id: "adobe-color",
      name: "Adobe Color",
      description: "Color wheel and schemes",
      icon: "fa-swatchbook",
      tags: ["free", "colors"],
      url: "https://color.adobe.com",
      category: "Colors",
    },
    {
      id: "figma",
      name: "Figma",
      description: "Collaborative interface design tool",
      icon: "fa-figma",
      tags: ["free", "ui-design"],
      url: "https://www.figma.com",
      category: "UI Design",
    },
  ],
};

// Export the resources object
if (typeof module !== "undefined" && module.exports) {
  module.exports = resources;
}
