const resources = {
  codingTools: [
    {
      id: "chatgpt",
      name: "ChatGPT",
      description:
        "Advanced language model for code explanation, debugging, and problem-solving",
      icon: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
      tags: ["ai", "free", "coding", "writing"],
      url: "https://chatgpt.com/",
      category: "AI Assistant",
    },

    {
      id: "deepseek",
      name: "DeepSeek Coder",
      description: "AI-powered code completion and generation tool",
      icon: "./images/deepseek.png",
      tags: ["ai", "free", "coding"],
      url: "https://chat.deepseek.com/",
      category: "Code Assistant",
    },
    {
      id: "gemini",
      name: "Google Gemini",
      description: "Google's multimodal AI for code assistance and generation",
      icon: "./images/gemini.png",
      tags: ["ai", "premium", "coding"],
      url: "https://cloud.google.com/vertex-ai",
      category: "Code Assistant",
    },
    {
      id: "github-copilot",
      name: "GitHub Copilot",
      description: "AI pair programmer that suggests code completions",
      icon: "./images/githubCopilt.png",
      tags: ["ai", "premium", "coding"],
      url: "https://github.com/features/copilot",
      category: "Code Assistant",
    },
    {
      id: "claude",
      name: "Claude AI",
      description: "Advanced AI assistant for coding and technical writing",
      icon: "./images/claude.png",
      tags: ["ai", "premium", "coding", "writing"],
      url: "https://www.anthropic.com/claude",
      category: "AI Assistant",
    },
    {
      id: "cursorai",
      name: "Cursor AI",
      description: "Advanced AI assistant for coding and technical writing",
      icon: "./images/cursor.png",
      tags: ["ai", "premium", "coding", "writing"],
      url: "https://www.cursor.com/",
      category: "AI Assistant",
    },

    // {
    //   id: "elevenLabs",
    //   name: "ElevenLabs",
    //   description:
    //     "Advanced language model for code explanation, debugging, and problem-solving",
    //   icon: "./images/eleven.png",
    //   tags: ["ai", "free", "coding", "writing"],
    //   url: "https://elevenlabs.io/?utm_source=google&utm_medium=cpc&utm_campaign=pakistan_brandsearch_brand_english&utm_id=22349494772&utm_term=elevenlabs&utm_content=brand_-_brand&gad_source=1&gad_campaignid=22349494772&gbraid=0AAAAAp9ksTFHDUe-Zg7zjrjgiVzDEfZxH&gclid=Cj0KCQjwxdXBBhDEARIsAAUkP6gJwBKsbqBj4Z9M-eEfVQqSP4KCEpN990jfSLzHcIDF7yPIKCGB2yQaArkCEALw_wcB",
    //   category: "AI Assistant",
    // },
  ],

  imageGeneration: [
    {
      id: "midjourney",
      name: "Midjourney",
      description: "known for artistic and stylized image generations.",
      icon: "./images/mid.png",
      tags: ["ai", "premium", "design"],
      url: "https://www.midjourney.com",
      category: "Design",
    },
    {
      id: "leonardo ai",
      name: "Leonardo Ai",
      description:
        "fast-growing platform for image generation, often used for game assets.",
      icon: "./images/leonardo.jfif",
      tags: ["ai", "free", "image"],
      url: "https://leonardo.ai/",
      category: "Design",
    },
    {
      id: "stablediffusion",
      name: "Stable Diffusion",
      description: "open-source, highly customizable image generation model.",
      icon: "./images/stable.jfif",
      tags: ["ai", "free", "image"],
      url: "https://stablediffusionweb.com/",
      category: "Design",
    },
    {
      id: "runway",
      name: "Runway ML",
      description: "offers image generation and AI video editing features.",
      icon: "./images/runway.png",
      tags: ["ai", "free", "image"],
      url: "https://runwayml.com/",
      category: "Design",
    },
    {
      id: "adobefirefly",
      name: "Adobe Firefly",
      description: "offers image generation and AI video editing features.",
      icon: "./images/adobeFirely.png",
      tags: ["ai", "free", "image"],
      url: "https://www.adobe.com/products/firefly.html",
      category: "Design",
    },
    {
      id: "dalle",
      name: "DALL·E 3",
      description: "AI image generation for design assets and illustrations",
      icon: "./images/dalle.png",
      tags: ["ai", "premium", "design"],
      url: "https://openai.com/dall-e-3",
      category: "Design",
    },
  ],

  freeResources: [
    {
      id: "unsplash",
      name: "Unsplash",
      description: "Beautiful free images & pictures",
      icon: "./images/unsplash.png",
      tags: ["free", "images"],
      url: "https://unsplash.com",
      category: "Images",
    },
    {
      id: "pexels",
      name: "Pexels",
      description: "Free stock photos & videos",
      icon: "./images/pexels.png",
      tags: ["free", "images"],
      url: "https://www.pexels.com",
      category: "Images",
    },
    {
      id: "pixabay",
      name: "Pixabay",
      description: "Free images & royalty-free stock",
      icon: "./images/pixaby.png",
      tags: ["free", "images"],
      url: "https://pixabay.com",
      category: "Images",
    },
    {
      id: "flaticon",
      name: "Flaticon",
      description: "Free vector icons & stickers",
      icon: "./images/flaticon.png",
      tags: ["free", "icons"],
      url: "https://www.flaticon.com",
      category: "Icons",
    },
    {
      id: "fontawesome",
      name: "Font Awesome",
      description: "Icon library and toolkit",
      icon: "./images/font.png",
      tags: ["free", "icons"],
      url: "https://fontawesome.com",
      category: "Icons",
    },
    {
      id: "material-icons",
      name: "Material Icons",
      description: "Google's Material Design icons",
      icon: "./images/material.png",
      tags: ["free", "icons"],
      url: "https://fonts.google.com/icons",
      category: "Icons",
    },
    {
      id: "heroicons",
      name: "Heroicons",
      description: "Beautiful hand-crafted SVG icons",
      icon: "./images/hero.png",
      tags: ["free", "icons"],
      url: "https://heroicons.com",
      category: "Icons",
    },
    {
      id: "figma-community",
      name: "Figma Community",
      description: "Free design resources and UI kits",
      icon: "./images/figma.png",
      tags: ["free", "ui-kits"],
      url: "https://www.figma.com/community",
      category: "UI Kits",
    },
  ],
  frontendFrameworks: [
    {
      id: "react",
      name: "React",
      description: "A JavaScript library for building user interfaces",
      icon: "./images/react.png",
      tags: ["free", "javascript", "frontend"],
      url: "https://reactjs.org",
      category: "JavaScript",
    },
    {
      id: "vue",
      name: "Vue.js",
      description: "Progressive JavaScript Framework",
      icon: "./images/vue.png",
      tags: ["free", "javascript", "frontend"],
      url: "https://vuejs.org",
      category: "JavaScript",
    },
    {
      id: "angular",
      name: "Angular",
      description: "Platform for building mobile and desktop web applications",
      icon: "./images/angular.png",
      tags: ["free", "javascript", "frontend"],
      url: "https://angular.io",
      category: "JavaScript",
    },
    {
      id: "tailwind",
      name: "Tailwind CSS",
      description: "Utility-first CSS framework",
      icon: "./images/tailwind.png",
      tags: ["free", "css"],
      url: "https://tailwindcss.com",
      category: "CSS",
    },
    {
      id: "bootstrap",
      name: "Bootstrap",
      description: "Popular CSS framework for responsive sites",
      icon: "./images/bootstrap.png",
      tags: ["free", "css"],
      url: "https://getbootstrap.com",
      category: "CSS",
    },
    {
      id: "chakra",
      name: "Chakra UI",
      description: "Simple, modular component library",
      icon: "./images/chakra.png",
      tags: ["free", "ui"],
      url: "https://chakra-ui.com",
      category: "UI",
    },
  ],
  backendFrameworks: [
    {
      id: "django",
      name: "Django",
      description: "High-level Python web framework",
      icon: "./images/django.png",
      tags: ["free", "python"],
      url: "https://www.djangoproject.com",
      category: "Python",
    },
    {
      id: "flask",
      name: "Flask",
      description: "Lightweight WSGI web application framework",
      icon: "./images/flask.png",
      tags: ["free", "python"],
      url: "https://flask.palletsprojects.com",
      category: "Python",
    },
    {
      id: "fastapi",
      name: "FastAPI",
      description: "Modern, fast web framework for Python",
      icon: "./images/fast.png",
      tags: ["free", "python"],
      url: "https://fastapi.tiangolo.com",
      category: "Python",
    },
    {
      id: "express",
      name: "Express.js",
      description: "Fast, unopinionated web framework for Node.js",
      icon: "./images/express.png",
      tags: ["free", "node"],
      url: "https://expressjs.com",
      category: "Node.js",
    },
    {
      id: "nestjs",
      name: "NestJS",
      description: "Progressive Node.js framework",
      icon: "./images/next.png",
      tags: ["free", "node"],
      url: "https://nestjs.com",
      category: "Node.js",
    },
  ],
  mobileDev: [
    {
      id: "flutter",
      name: "Flutter",
      description: "Google's UI toolkit for cross-platform apps",
      icon: "./images/flutter.png",
      tags: ["free", "cross-platform"],
      url: "https://flutter.dev",
      category: "Cross-Platform",
    },
    {
      id: "react-native",
      name: "React Native",
      description: "Build native apps using React",
      icon: "./images/reactn.png",
      tags: ["free", "cross-platform"],
      url: "https://reactnative.dev",
      category: "Cross-Platform",
    },
    {
      id: "swiftui",
      name: "SwiftUI",
      description: "Apple's UI framework for iOS",
      icon: "./images/swift.png",
      tags: ["free", "ios"],
      url: "https://developer.apple.com/xcode/swiftui",
      category: "iOS",
    },
    {
      id: "jetpack",
      name: "Jetpack Compose",
      description: "Modern UI toolkit for Android",
      icon: "./images/jet.png",
      tags: ["free", "android"],
      url: "https://developer.android.com/jetpack/compose",
      category: "Android",
    },
  ],
  gameDev: [
    {
      id: "unity",
      name: "Unity",
      description: "Cross-platform game development engine",
      icon: "./images/unity.png",
      tags: ["free", "engines"],
      url: "https://unity.com",
      category: "Engines",
    },
    {
      id: "phaser",
      name: "Phaser",
      description: "HTML5 game framework",
      icon: "./images/phaser.jfif",
      tags: ["free", "frameworks"],
      url: "https://phaser.io",
      category: "Frameworks",
    },
  ],
  datavisualization: [
    {
      id: "powerBi",
      name: "Power Bi",
      description:
        "Microsoft’s business intelligence and data visualization tool.",
      icon: "./images/power.jfif",
      tags: ["ai", "premium", "design"],
      url: "https://app.powerbi.com/singleSignOn?ru=https%3A%2F%2Fapp.powerbi.com%2F%3FnoSignUpCheck%3D1",
      category: "Design",
    },
       {
      id: "tableau",
      name: "Tableau",
      description:
        "Interactive dashboards, visual analytics.",
      icon: "./images/tableau.png",
      tags: ["ai", "premium", "design"],
      url: "https://app.powerbi.com/singleSignOn?ru=https%3A%2F%2Fapp.powerbi.com%2F%3FnoSignUpCheck%3D1",
      category: "Design",
    },
  ],
  designTools: [
    {
      id: "coolors",
      name: "Coolors",
      description: "Color schemes generator",
      icon: "./images/coolor.png",
      tags: ["free", "colors"],
      url: "https://coolors.co",
      category: "Colors",
    },
    {
      id: "adobe-color",
      name: "Adobe Color",
      description: "Color wheel and schemes",
      icon: "./images/adobeColor.png",
      tags: ["free", "colors"],
      url: "https://color.adobe.com",
      category: "Colors",
    },
    {
      id: "figma",
      name: "Figma",
      description: "Collaborative interface design tool",
      icon: "./images/figma.png",
      tags: ["free", "ui-design"],
      url: "https://www.figma.com",
      category: "UI Design",
    },
  ],
};

// Export the resources object
if (typeof module !== "undefined" && module.exports) {
  module.exports = resources;
}
